### ISSUE TITLE
network analyzer nil point

### ISSUE THREAD

**Issue by blue-troy** [KindlingProject/kindling#401]
**Describe the bug**
network analyzer nil point

**Screenshots**

**What config did you use?**
Config: (e.g. the yaml config file)

**Logs**
Please attach the logs by running the following command:
```
kubectl logs -f kindling-agent-xxx(replace with your podname) -n kindling -c kindling-collector

2022-12-16T08:42:08.120656454+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2022-12-16T08:42:08.120709105+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaee839]
2022-12-16T08:42:08.120720095+08:00 stderr F
2022-12-16T08:42:08.120729087+08:00 stderr F goroutine 128 [running]:
2022-12-16T08:42:08.120758518+08:00 stderr F github.com/Kindling-project/kindling/collector/pkg/component/analyzer/network.(*NetworkAnalyzer).getRecordWithSinglePair(0xc0003aa420
, 0xc001ff9b00, 0xc0023736c8, {0x1b134d3, 0x0}, 0xc)
2022-12-16T08:42:08.120781491+08:00 stderr F    /kindling/collector/pkg/component/analyzer/network/network_analyzer.go:616 +0xe99
2022-12-16T08:42:08.120791015+08:00 stderr F github.com/Kindling-project/kindling/collector/pkg/component/analyzer/network.(*NetworkAnalyzer).parseMultipleRequests(0xc002373848,
0xc001ff9b00, 0xc00103e480)
2022-12-16T08:42:08.120799386+08:00 stderr F    /kindling/collector/pkg/component/analyzer/network/network_analyzer.go:495 +0x891
2022-12-16T08:42:08.120816296+08:00 stderr F github.com/Kindling-project/kindling/collector/pkg/component/analyzer/network.(*NetworkAnalyzer).parseProtocol(0x187d100, 0xc002373a0
0, 0xc00054fda0)
2022-12-16T08:42:08.120827133+08:00 stderr F    /kindling/collector/pkg/component/analyzer/network/network_analyzer.go:413 +0x40b
2022-12-16T08:42:08.120853127+08:00 stderr F github.com/Kindling-project/kindling/collector/pkg/component/analyzer/network.(*NetworkAnalyzer).parseProtocols(0xc0003aa420, 0xc001f
f9b00)
2022-12-16T08:42:08.120868886+08:00 stderr F    /kindling/collector/pkg/component/analyzer/network/network_analyzer.go:361 +0xc5
2022-12-16T08:42:08.120876602+08:00 stderr F github.com/Kindling-project/kindling/collector/pkg/component/analyzer/network.(*NetworkAnalyzer).distributeTraceMetric(0xc0003aa420,
0xc001ff9b00, 0xc002831380)
2022-12-16T08:42:08.120891993+08:00 stderr F    /kindling/collector/pkg/component/analyzer/network/network_analyzer.go:336 +0x32e

```
**Environment (please complete the following information)**
- Kindling agent git commit id: 227f9d73
- Kindlinng-falcon-lib version
- Node OS version centos7
- Node Kernel version 3.10.0-1062.12.1.el7.x86_64
- Kubernetes version v1.23.10

**Additional context**
Add any other context about the problem here, like appliction protocol.

**Comment by hocktea214** [comment]
This is a method design issue which confused mp and mps.
> getRecordWithSinglePair(mps, mp, protocol, attributes)

The mps is bringed to get natTuple info.
```
if nil != mps.natTuple {
    labels.UpdateAddStringValue(constlabels.DnatIp, mps.natTuple.ReplSrcIP.String())
    labels.UpdateAddIntValue(constlabels.DnatPort, int64(mps.natTuple.ReplSrcPort))
}
```

The correct way to fix the all confusing useage in this method is to add natTuple info into mp and remove mps
```
getRecordWithSinglePair(mp *messagePair, protocol string, attributes *model.AttributeMap) *model.DataGroup {}

type messagePair struct {
	request  *model.KindlingEvent
	response *model.KindlingEvent
        natTuple  *conntracker.IPTranslation
}
```

**Comment by blue-troy** [comment]
> 

yes, naming problem occurs multiple times. kindling should pay more attention to this kind problem.

**Comment by dxsup** [comment]
Thanks for your reminder. We appreciate any PRs for improving naming or readability issues.
